apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-deployment
  namespace: notes-app-namespace
  labels:
    app: notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      imagePullSecrets:                          # image pull because i am using rancher private registry
        - name: dockerhub-secret
      containers:
      - name: notes-app
        image: rohitbatham/notes-app-k8s
        ports:
        - containerPort: 8000
